Repository algolia/algoliasearch-client-csharp, pull requests merged in 2019-07, with the labels that each got.

#620 Internal: Improve test assertions
  src/Algolia.Search.Test/EndToEnd/Analytics/AnalyticsAATest.cs
  src/Algolia.Search.Test/EndToEnd/Analytics/AnalyticsAbTest.cs
  src/Algolia.Search.Test/EndToEnd/ApiKeys/SecuredApiKeyTest.cs
  src/Algolia.Search.Test/EndToEnd/Client/ApiKeysTest.cs
  src/Algolia.Search.Test/EndToEnd/Client/LogsTest.cs
  src/Algolia.Search.Test/EndToEnd/Client/MultipleOperationsTest.cs
  src/Algolia.Search.Test/EndToEnd/Index/BatchingTest.cs
  src/Algolia.Search.Test/EndToEnd/Index/IndexingTest.cs
  src/Algolia.Search.Test/EndToEnd/Index/MultiClusterManagementTest.cs
  src/Algolia.Search.Test/EndToEnd/Index/QueryRulesTest.cs
  src/Algolia.Search.Test/EndToEnd/Index/ReplacingTest.cs
  src/Algolia.Search.Test/EndToEnd/Index/SearchTest.cs
  src/Algolia.Search.Test/EndToEnd/Index/SynonymsTest.cs
Labels: Chore, Do not merge

#629 fix: fix typo (WriteTimeut → WriteTimeout)
  src/Algolia.Search/Transport/HttpTransport.cs
  src/Algolia.Search/Utils/Defaults.cs
Labels: Chore

#628 feat(index): add exists method
  src/Algolia.Search.Test/EndToEnd/Index/ExistsTest.cs
  src/Algolia.Search/Clients/ISearchIndex.cs
  src/Algolia.Search/Clients/SearchIndex.cs
Labels: API feature, Chore

#633 fix: missing using block in HttpRequester
  src/Algolia.Search/Http/AlgoliaHttpRequester.cs
Labels: Bug, Chore

#634 fix: missing catch clause in httpRequester
  src/Algolia.Search.Test/RetryStrategyTest/RetryStrategyTest.cs
  src/Algolia.Search/Http/AlgoliaHttpRequester.cs
  src/Algolia.Search/Http/AlgoliaHttpResponse.cs
  src/Algolia.Search/Transport/HttpTransport.cs
  src/Algolia.Search/Transport/RetryStrategy.cs
Labels: Bug, Do not merge

#639 internal: formatting rules
  .editorconfig
  src/Algolia.Search.Test/EndToEnd/Index/MultiClusterManagementTest.cs
  src/Algolia.Search/Clients/SearchIndex.cs
Labels: Chore
